[workspace]
members = ["examples/*"]

[package]
name = "physac"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = { version = "*", optional = true }

[features]
default = ["raylib"]
raylib = ["dep:raylib"]
no_threads = []
debug = []
