[package]
name = "physics_restitution"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5"
physac = { version = "0.1.0", features = ["raylib", "debug"] }

[features]
default = ["phys_thread"]
phys_thread = ["physac/phys_thread"]
